apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: auth-ms
  name: auth-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-ms
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: auth-ms
    spec:
      containers:
      - image: southamerica-west1-docker.pkg.dev/ms-products-launcher/image-registry/auth-ms
        name: auth-ms
        env:
        - name: PORT
          value: "3004"
        - name: NATS_SERVERS
          value: "nats://nats"
        - name: DATABASE_URL
          valueFrom:   
            secretKeyRef:
              name: auth-secrets
              key: database_url
        - name: JWT_SECRET
          valueFrom:   
            secretKeyRef:
              name: auth--jwt-secrets
              key: jwt_secret              
        resources: {}
status: {}
