apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: payments-ms
  name: payments-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-ms
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: payments-ms
    spec:
      containers:
      - image: southamerica-west1-docker.pkg.dev/ms-products-launcher/image-registry/payments-ms
        name: payments-ms
        env:
        - name: PORT
          value: "3004"
        - name: NATS_SERVERS
          value: "nats://nats"
        - name: URL_SUCCESS
          value: "http://localhost:3003/api/payments/success"
        - name: URL_CANCEL
          value: "http://localhost:3003/api/payments/cancel"
        - name: STRIPE_SECRET
          valueFrom:   
            secretKeyRef:
              name: payments-secrets
              key: stripe_secret
        - name: ENDPOINT_SECRET
          valueFrom:
            secretKeyRef:
              name: payments-secrets
              key: enpoint_secret
        resources: {}
status: {}
